server:
  port: 4000

management:
  endpoints:
    web:
      exposure:
        include: gateway
  endpoint:
    gateway:
      enabled: true # default value

spring:
  cloud:
    gateway:
      routes:
        - id: login
          uri: http://localhost:5003/oauth/token
          predicates:
            - Path=/oauth/token

        - id: CreateUser
          uri: http://localhost:5000/api/v1/user/createUser
          predicates:
            - Path=/api/v1/user/createUser

        - id: UpdateUser
          uri: http://localhost:5000/api/v1/user/updateUser/**
          predicates:
            - Path=/api/v1/user/updateUser/**

        - id: FindUserByName
          uri: http://localhost:5002/api/v1/user/name/**
          predicates:
            - Path=/api/v1/user/name

        - id: AddProfile
          uri: http://localhost:5000/skill-tracker/api/v1/engineer/add-profile
          predicates:
            - Path=/skill-tracker/api/v1/engineer/add-profile

        - id: UpdateProfile
          uri: http://localhost:5000/skill-tracker/api/v1/engineer/update-profile/**
          predicates:
            - Path=/skill-tracker/api/v1/engineer/update-profile/**
            
        - id: deleteProfile
          uri: http://localhost:5000/skill-tracker/api/v1/engineer/delete-profile/**
          predicates:
            - Path=/skill-tracker/api/v1/engineer/delete-profile/**

        - id: GetProfileByCriteria
          uri: http://localhost:5002/skill-tracker/api/v1/admin/**
          predicates:
            - Path=/skill-tracker/api/v1/admin/**

        - id: cmd actuator
          uri: http://localhost:5000/actuator/**
          predicates:
            - Path=/actuator

        - id: swagger-ui
          uri: http://localhost:5000/swagger-ui/**
          predicates:
            - Path=/swagger-ui