server:
  port: 5002

spring:
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: engineerprofile
  
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
      
  main:
    allow-bean-definition-overriding: true

security:
  oauth2:
    resource:
      jwt:
        key-value: skilltrackerSigningKey